DROP TABLE Consist_of CASCADE;
DROP TABLE Sell CASCADE;

DROP TABLE Prescription CASCADE;
DROP TABLE Doctor CASCADE;

DROP TABLE Drug CASCADE;
DROP TABLE Ph_company CASCADE;

DROP TABLE Pharmacy CASCADE;
